openapi: 3.0.0
info:
  description: "wdb+ REST API v2 (wdb+ > v4.0) – see https://github.com/dariok/wdbplus for details"
  version: "2.0"
  title: "wdb+ API"
  # termsOfService: "see instance"
  contact:
    url: https://github.com/dariok/wdbplus
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://wdbplus.instance/exist/restxq/edoc/v2
tags:
  - name: annotations
    description: Concerning Hobbits
  - name: projects
    description: Operations on wdb+ projects
  - name: entities
    description: Operations on entities
  - name: resources
    description: Operations on resources (usually texts)
  - name: search
    description: Full text search

paths:
  # TODO:
  # /admin

  /annotations:
    post:
      tags:
        - annotations
      summary: Add a new full text annotation
      description: This creates full text annotations only. Changes to the file, including entity markup, must use PATCH /resources/{id}
      operationId: TODO
      requestBody:
        description: the full text annotation to be added
        required: true
        content:
          application/json:
            schema: #TODO
          application/xml:
            schema: #TODO
    #   responses:
    #     "201":
    #       description: Annotation has been created
    #     "400":
    #       description: Invalid input
  /annotations/{annotation}:
    parameters:
      - name: "annotation"
        in: path
        description: The ID of the annotation
        schema:
          type: string
        required: true
    get:
      tags:
        - annotations
      summary: Get annotation by ID
      operationId: TODO getAnnotationById
    #   responses:
    #     "200":
    #       description: Annotation has been found
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/Annotation"
    #     "404":
    #       description: No ID found by this ID
    delete:
      tags:
        - annotations
      summary: Delete an annotation
      operationId: #TODO deleteAnnotation
    #   responses:
    #     "200":
    #       description: The annotation has been deleted
    #     "404":
    #       description: This annotation was not found
  /annotations/forFile/{id}:
    parameters:
      - "$ref": "#/components/parameters/id"
    get:
      tags:
        - annotations
      summary: List of annotations related to a file
      operationId: #TODO
    #   responses:
    #     "200":
    #       description: Found annotations for this file
    #       content:
    #         application/json:
    #           schema:
    #             $ref: #TODO
    #     "204":
    #       description: No annotations for this file
    #     "404":
    #       description: File not found
  
  /projects:
    get:
      tags:
        - projects
      summary: List all projects
      operationId: #TODO listProjects
    #   responses:
    #     "200":
    #       description: Contains a list of projects
    #       content: #TODO
  /projects/{ed}:
    parameters:
      - "$ref": "#/components/parameters/ed"
    get:
      tags:
        - projects
      summary: Project info by ID
      operationId: #TODO
    delete:
      tags:
        - projects
      summary: Delete project
      operationId: #TODO
    put:
      tags:
        - projects
      summary: Create project with given ID
      description: This creates a new project with the ID given as ed and the necessary meta data in the request body
      operationId: #TODO
      requestBody:
        description: The necessary data for the project to be created
        required: true
        content:
          application/xml:
            schema: #TODO
  /projects/{ed}/nav:
    parameters:
      - "$ref": "#/components/parameters/ed"
    get:
      tags:
        - projects
      summary: Get project navigation
      operationId: #TODO

  /entities:
    get:
      tags:
        - entities
      summary: Query entities in global registry
      operationId: #TODO
      parameters:
        - "$ref": "#/components/parameters/q"
        - "$ref": "#/components/parameters/type"
  /entities/project/{ed}:
    parameters:
      - "$ref": "#/components/parameters/ed"
      - "$ref": "#/components/parameters/q"
      - "$ref": "#/components/parameters/type"
    get:
      tags:
        - entities
      summary: Query entities in a project’s registry
      operationId: #TODO
  /entities/project/{ed}/refs/{entity}:
    parameters:
      - "$ref": "#/components/parameters/ed"
      - "$ref": "#/components/parameters/entity"
    get:
      tags:
        - entities
      summary: List texts in a project referring to an entity
      operationId: #TODO
  /entities/resource/{id}/refs/{entity}:
    parameters:
      - "$ref": "#/components/parameters/id"
      - "$ref": "#/components/parameters/entity"
    get:
      tags:
        - entities
      summary: List all fragments containing a reference to an entity
      operationId: #TODO

  /resources/{id}:
    parameters:
      - "$ref": "#/components/parameters/id"
    get:
      tags:
        - resources
      summary: Get resource by ID
      operationId: #TODO
    put:
      tags:
        - resources
      summary: Create or update a file
      operationId: #TODO
      requestBody:
        description: Create or replace a file with the ID given in id and the content in the request body
        required: true
        content:
          application/xml:
            schema: #TODO
    patch:
      tags:
        - resources
      summary: Change a fragment from a file
      operationId: #TODO
      requestBody:
        description: The replacement XML fragment 
        required: true
        content:
          application/xml:
            schema: #TODO or use an example
    head:
      tags:
        - resources
      summary: Preflight request
      operationId: #TODO
    options:
      tags:
        - resources
      summary: Preflight request
      operationId: #TODO
    delete:
      tags:
        - resources
      summary: delete a file
      operationId: #TODO
  /resources/{id}/views:
    parameters:
      - "$ref": "#/components/parameters/id"
    get:
      tags:
        - resources
      summary: List views for a file
      operationId: #TODO
  /resources/{id}/views/{view}:
    parameters:
      - "$ref": "#/components/parameters/id"
      - name: view
        in: path
        description: The ID of the view to be invoked
        schema:
          type: string
        required: true
    get:
      tags:
        - resources
      summary: Get resource as represented by view
      operationId: #TODO
  /resources/byPid/{pid}:
    parameters:
      - name: "pid"
        in: path
        description: The externally defined persistend ID of a file
        schema:
          type: string
        required: true
    get:
      tags:
        - resources
      summary: Return our ID for a external PID
      operationId: #TODO

  /search/ft/project/{ed}:
    parameters:
      - "$ref": "#/components/parameters/ed"
      - "$ref": "#/components/parameters/q"
    get:
      tags:
        - search
      summary: List files in project containing text
      operationId: #TODO
  /search/ft/resource/{id}:
    parameters:
      - "$ref": "#/components/parameters/id"
      - "$ref": "#/components/parameters/q"
    get:
      tags:
        - search
      summary: List fragments in file containing text
      operationId: #TODO


components:
  parameters:
    id:
      name: "id"
      in: path
      description: The ID of the
      schema:
        type: string
      required: true
    ed:
      name: "ed"
      in: path
      description: The ID of the project
      schema:
        type: string
      required: true
    entity:
      name: "entity"
      in: path
      description: The ID of the entity
      schema:
        type: string
      required: true
    q:
      name: q
      in: query
      schema:
        type: string
      description: query or filter by name / title
    type:
      name: "type"
      in: path
      description: The type of entity
      schema:
        enum:
          - per
          - pla
          - org
          - bib
          - evt
      required: true
  
#   requestBodies:
#     Annotation:
#       required: true
#       description: A new annotation for a file
#       content:
#         application/json:
#           schema:
#             $ref: "#/components/schemas/Annotation"
  
#   schemas:
#     Annotation:
#       type: object
#       required:
#         - id #file ID
#         - content #text of the annotation
#       properties:
#         id:
#           type: string
#           description: "The ID of the file"
#         content:
#           type: string
#           description: "The text of the annotation"
