OPTIONS http://localhost:8080/exist/apps/edoc/api/v2/projects

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects
Accept: application/xml

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects
Accept: application/json

###
# supposed to fail – no media type given
POST http://localhost:8080/exist/apps/edoc/api/v2/projects/data/subprojects

###
# supposed to fail – POST must not have an ID
POST http://localhost:8080/exist/apps/edoc/api/v2/projects/data/subprojects
Content-Type: application/json

{
  "title": "New Project",
  "short": "short title",
  "id": "newCollectionName"
}

###
# supposed to fail – parent not found
POST http://localhost:8080/exist/apps/edoc/api/v2/projects/dat/subprojects
Content-Type: application/json

{
  "title": "New Project",
  "short": "short title",
  "collection": "newCollectionName"
}

###
# supposed to succeed
POST http://localhost:8080/exist/apps/edoc/api/v2/projects/data/subprojects
Content-Type: application/json

{
  "title": "New Project",
  "short": "short title",
  "collection": "newCollectionName"
}

###
# supposed to fail – project ID in use
PUT http://localhost:8080/exist/apps/edoc/api/v2/projects/data/subprojects/documentation
Content-Type: application/json

{
  "title": "New Project",
  "short": "short title",
  "collection": "newCollectionName"
}

###
# supposed to succeed
PUT http://localhost:8080/exist/apps/edoc/api/v2/projects/pb006000/subprojects/pb006001
Content-Type: application/json

{
  "title": "Vier Bücher von Wahrem Christentum, Band 1",
  "short": "BWC I",
  "collection": "pb006001"
}

###

POST http://localhost:8080/exist/apps/edoc/api/v2/login
Content-Type: multipart/form-data; boundary=----test----

------test----
Content-Disposition: form-data; name="user"

admin
------test----
Content-Disposition: form-data; name="password"

admin
------test------

###
GET http://localhost:8080/exist/apps/edoc/api/v2/logout

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/data/views
Accept: application/json

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb006001
Accept: application/xml

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb006001/subprojects
Accept: application/xml

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb006001/views/default
Accept: application/xml

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb001740/views/start
Accept: text/html

###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb001740/views/navigation
Accept: text/html
###

GET http://localhost:8080/exist/apps/edoc/api/v2/projects/pb006001/resources
Accept: application/json

###

DELETE http://localhost:8080/exist/apps/edoc/api/v2/projects/project

###

OPTIONS http://localhost:8080/exist/apps/edoc/api/v2/projects
Origin: http://exist.localhost:8080

###

POST http://localhost:8080/exist/apps/edoc/api/v2/projects/pb001741/resources
Content-Type: multipart/form-data; boundary=wdb

--wdb
Content-Disposition: form-data; name="path"

edition
--wdb
Content-Disposition: form-data; name="file"; filename="17410105.xml"
Content-Type: application/xml

#< ../edoc/webstart.xql
< ../edoc/config.xml
#< /home/kampkaspar/git/dat/steps/50_tokenized/1741/17410105.xml
--wdb--

###

PUT http://localhost:8080/exist/apps/edoc/api/v2/projects/pb001741/resources/pb001741-0105
Content-Type: multipart/form-data; boundary=wdb

--wdb
Content-Disposition: form-data; name="path"

edition/01
--wdb
Content-Disposition: form-data; name="file"; filename="17410105.xml"
Content-Type: application/xml

# < ../edoc/config.xml
< /home/kampkaspar/git/dat/steps/50_tokenized/1741/17410105.xml
--wdb--

###

PUT http://localhost:8080/exist/apps/edoc/api/v2/projects/pb001174/resources/pb001174-0001
Content-Type: application/xml

< /home/kampkaspar/git/dat/steps/50_tokenized/1741/17410105.xml
