# Supposed to be successful (200 or 204)
# TODO: When documentation is present, use this as a use case
GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/project/data?q=rahn
Accept: application/xml

###
# supposed to return 404
GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/project/datas?q=rahn
Accept: application/xml

###

GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/project/data?q=fichte
Accept: application/json
###

GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/project/data?q=fichte
Accept: text/html

###

GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/resource/pa000032-0194?q=fichte
Accept: application/xml
###

GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/resource/pa000032-0210?q=rahn
Accept: application/json
###

GET http://localhost:8080/exist/apps/edoc/api/v2/search/ft/resource/pa000032-0210?q=rahn
Accept: text/html
