GET https://tueditions.ulb.tu-darmstadt.de/r/edoc/collection/pa000023/nav.xml

###
GET https://tueditions.ulb.tu-darmstadt.de/r/edoc/collection/pa000018/nav.xml

###
GET https://tueditions.ulb.tu-darmstadt.de/r/edoc/collection/pa000019/nav.html

###

GET https://exist.ulb.tu-darmstadt.de/2/r/edoc/collection/pa000009/nav.xml