(: wdbplus: load parts of start.html by means of project specifics
 : created: 2019-02-20
 : creator: DK - Dario Kampkaspar <dario.kampkaspar@oeaw.ac.at>
 : sources: https://github.com/dariok/wdbplus
 : changes:
 :          - 2019-06-08: module now used in function.html context
 :          - 2019-06-28: enable use of templating functions within project
 :                        specific HTML files
 :          – 2023-03-01: enable the use of start.xsl (instance specific or global) to create from wdbmeta.xml
 :)
xquery version "3.1";

module namespace wdbst = "https://github.com/dariok/wdbplus/start";

import module namespace r2p       = "https://github.com/dariok/wdbplus/rest2/projects"  at "../rest2/projects.xqm";
import module namespace wdb       = "https://github.com/dariok/wdbplus/wdb"             at "app.xqm";
import module namespace templates = "http://exist-db.org/xquery/html-templating";

declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
declare namespace router = "http://e-editiones.org/roaster/router";
declare namespace wdbPF  = "https://github.com/dariok/wdbplus/projectFiles";

(: get the left part of the start page from either projectSpec HTML, projectSpec function or a generic heading :)
declare function wdbst:getStartLeft( $node as node(), $model as map(*) ) as node()* {
  comment { "created in start.xqm, " || $node/@data-template },
  if ( doc-available($model("projectResources") || '/html/startLeft.html') ) then
    templates:apply(doc($model("projectResources") || '/html/startLeft.html'),  $wdbst:lookup, $model)
  else if ( wdb:findProjectFunction($model, "wdbPF:getStartLeft", 1) ) then
    (wdb:getProjectFunction($model, "wdbPF:getStartLeft", 1))($model)
  else (
    <h2>Inhalt</h2>,
    map:get(r2p:projectView(map{ "path": $model?infoFileLoc, "parameters": map { "view": "navigation", "ed": $model?ed }, "Accept": "text/html" }), xs:QName("router:RESPONSE_BODY"))
  )
};

(: get the main part of the start page from either projectSpec HTML, projectSpec function or return an empty seq :)
declare function wdbst:getStart ( $node as node(), $model as map(*) ) as node()* {
  comment { "created in start.xqm, " || $node/@data-template },
  if ( doc-available($model("projectResources") || '/html/startRight.html') ) then
    templates:apply(doc($model("projectResources") || '/html/startRight.html'), $wdbst:lookup, $model)
  else if ( wdb:findProjectFunction($model, "wdbPF:getStart", 1) ) then
    (wdb:getProjectFunction($model, "wdbPF:getStart", 1))($model)
  else
    map:get(r2p:projectView(map{ "path": $model?infoFileLoc, "parameters": map { "view": "start", "ed": $model?ed }, "Accept": "text/html" }), xs:QName("router:RESPONSE_BODY"))
};

(: header is generated by function.xqm :)

(: we need a lookup function for the templating system to work :)
declare variable $wdbst:lookup := function( $functionName as xs:string, $arity as xs:int ) {
  function-lookup(xs:QName($functionName), $arity)
};
